### ISSUE TITLE
Implementing Action Masking in RL Training with AnyLogic

### ISSUE THREAD

**Issue by Spacy-h** [MarcEscandell/ALPypeRL#11]
Hi,

I am currently training a reinforcement learning (RL) model using AnyLogic. I want to implement action masking to prevent the RL agent from taking illegal actions during training. This is crucial for ensuring that the RL model can effectively learn in scenarios where many actions are illegal.

Could you provide guidance or suggestions on how to implement action masking in this context?

Thank you!

**Comment by MarcEscandell** [comment]
Hi @Spacy-h! Thanks for reaching out.

Currently, this feature is not supported by _alpyperl_. However, I will definitely consider adding it in the future. Do allow me some time to do a bit more research on it. Do you have any recommended resources/examples? I found this one from the _PettingZoo_, [here](https://pettingzoo.farama.org/tutorials/custom_environment/3-action-masking/).

As far as I understand, there's two ways to handle _illegal_ or _undesirable_ actions in RL:

* Penalty-based
* Action masking

In the past, I have mostly used the _penalty-based_ approach as it is simple to implement. If the agent takes an _illegal_ action, the environment returns a penalty (usually a negative reward) and leaves the agent in the same state or imposes some form of consequence. Over time, the agent learns that these actions are sub-optimal because they lead to penalties, and it reduces the frequency of selecting them.

Nevertheless, it comes at a price: inefficient learning (exploring _illegal_ actions) and some sort of instability if the penalty is not tuned correctly. But the worst one is that it doesn't completely remove the possibility of taking an _illegal_ action, which could be very dangerous if not handled correctly in production.

In any case, the quickest solution I can give/suggest you right now is to _hardcode_ your rules in the _step_ function ([here](https://github.com/MarcEscandell/ALPypeRL/blob/main/alpyperl/gym/envs/anylogic_env.py)).

Let me know if that works for you!

**Comment by Spacy-h** [comment]
Hi @MarcEscandell !
Thanks for the reply.
I am trying the Penalty-based approach( a high negative reward). However, during the evaluation phase, if the RL agent takes an action that incurs a penalty, it tends to get stuck repeating the same action for the entire simulation period. I am asking for actions at fixed intervals. Interestingly, this issue does not occur during the training phase.

Could you help me understand why this might be happening and suggest how I can fix it?

**Comment by MarcEscandell** [comment]
mmmm... that's pretty odd! May I know what `alpyperl` version are you using? When plotting the reward function during training, do you see a clear convergence?

**Comment by Spacy-h** [comment]
Hi @MarcEscandell 
I am using AnyLogic version 8.9 and the corresponding alpyperl version compatible with it. I can see convergence in the graph. I am attaching the alpyperl version as seen in AnyLogic and the graph observed during the training phase.
![image](https://github.com/user-attachments/assets/86478eaa-2fbb-4496-ab38-f57d2477b2e6)
![image](https://github.com/user-attachments/assets/deec66f7-8e41-43f6-a0d2-78a50f3fbd97)

**Comment by MarcEscandell** [comment]
Sorry @Spacy-h, I meant the python version of `alpyperl`.

**Comment by Spacy-h** [comment]
I am using alpyperl 1.1.2

**Comment by MarcEscandell** [comment]
mmmm... yeah you are using the latest version. I'm not sure why you are facing that issue then. Maybe it requires longer training to ensure it avoids the forbidden actions?

**Comment by Spacy-h** [comment]
Hi @MarcEscandell 
The issue has been resolved after uninstalling and reinstalling the alpyperl package. Thanks for your support!
Also, the high penalty reward approach works after a longer training period, although the RL agent occasionally took some illegal actions.

Would it be possible for you to share access to the ALPypeRL Connector Model? I'd like to contribute by adding action masking to the ALPypeRL Connector.
Thanks again!

**Comment by MarcEscandell** [comment]
Hei! Happy to hear that the issue has been resolved.

Sure, I can give you access to the ALPypeRL Connector repo :)

**Comment by Spacy-h** [comment]
Thank you! I'd be happy to receive access to the ALPypeRL Connector repo.
Looking forward to it, and thanks again for your help! :)
