### ISSUE TITLE
Action Spaces folder not be generated when checkpointing

### ISSUE THREAD

**Issue by jacobtw2** [MarcEscandell/ALPypeRL#9]
To perform evaluation you need to have a folder called Action Spaces which gets generated by the model. However it only seems to get created when policy.stop() is called. 

This is an issue because in some cases I am running training for a long time and may want to cancel it or sometimes my computer crashes when running training for a day or more. I have regular checkpoints because of this

Is the action spaces folder always going to be the same if I don't change the structure of the model or does it depend on the training?

Could I just load my latest checkpoint and then run 1 more loop in order to get it to generate the action space folder?

**Comment by MarcEscandell** [comment]
Hi Jacob! Thanks for your message!

> To perform evaluation you need to have a folder called Action Spaces which gets generated by the model. However it only seems to get created when policy.stop() is called.

You are absolutely right here. This folder is only generated when `policy.stop()` is called.

> This is an issue because in some cases I am running training for a long time and may want to cancel it or sometimes my computer crashes when running training for a day or more. I have regular checkpoints because of this

Even myself I have faced exactly the same issue. A way to solve this problem was to generate the `alpyperl_spaces` folder when the policy is checkpointed. However, I could not find how to execute any code from the environment. The only way was when `policy.stop()` is called, creating the problems that you just mention. I am thinking of an alternative way to manually generate this folder. However, it will be a bit less nice, as you have to manually execute the code.

By the way, just to share a bit more insights on what the `alpyperl_spaces` folders contains: since the latest release of alpyperl, the user is now able to define the spaces from AnyLogic. This is great, but brings a new challenge, which is to inform the python side of such environment definition. This is also applicable when _evaluating_ your policy. That is the reason for the existence of such files.

> Is the action spaces folder always going to be the same if I don't change the structure of the model or does it depend on the training?

Since the folder just contains the action and observation spaces definition, in case you don't change it, in general you should be able to simply copy paste it. Sometimes what I might do is to simply create a one step training so the model generates this folder and then I copy paste it into the checkpoint that run for long and somewhat crashed.

As I said, I will be looking into an alternative way to easily create this folder without having to resource to this workaround.

Thanks again for highlighting this issue!

**Comment by MarcEscandell** [comment]
Hei Jacob! In **version 1.1.2** the _alpyperl_spaces_ is now being created when the first anylogic environment is created. This should fix the issue of having to wait for `policy.close()` being called. Thanks for raising this issue. Happy modelling!
